# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('notes', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField()),
                ('scheduled_bid_date', models.DateTimeField()),
                ('tentative_start', models.DateField()),
                ('actual_start', models.DateField()),
                ('completion_date', models.DateField()),
                ('down_payment_amount', models.FloatField(default=0)),
                ('down_payment_date', models.DateField()),
                ('final_payment_amount', models.FloatField(default=0)),
                ('final_payment_date', models.DateField()),
                ('status', models.CharField(max_length=2000)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
