# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('cost', models.FloatField()),
                ('measurement', models.CharField(max_length=30)),
                ('protected', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
