# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
