# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
