# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20170105_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
