# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
