# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_protected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['description']},
        ),
    ]
