# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_delete_servicecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='protected',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
