# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='bid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='bid.Bid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=photo.models.generate_filename),
        ),
    ]
