# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, help_text='Enter Payment Description', max_length=100)),
                ('amount', models.FloatField(blank=True, help_text='Enter Payment Amount', max_length=128)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Bid')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
