# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_auto_20170204_2042'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bid.Bid'),
            preserve_default=False,
        ),
    ]
