# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
