# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='customer',
        ),
        migrations.AddField(
            model_name='journal',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Bid'),
            preserve_default=False,
        ),
    ]
