# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ['description']},
        ),
    ]
