# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.FloatField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('total', models.FloatField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Bid')),
            ],
            options={
                'verbose_name_plural': 'BidItems',
            },
        ),
    ]
