# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='biditem',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
