# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid_item', '0003_biditem_job_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biditem',
            old_name='job_name',
            new_name='job_type',
        ),
    ]
