# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, help_text='Enter the street address', max_length=128)),
                ('city', models.CharField(blank=True, help_text='Enter the city', max_length=50)),
                ('state', models.CharField(blank=True, help_text='Enter the 2 digit state abbreviation', max_length=2)),
                ('zip', models.CharField(blank=True, help_text='Enter the 5 digit zipcode', max_length=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
