# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scheduled_bid_date', models.DateTimeField(blank=True, null=True)),
                ('tentative_start', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('down_payment_amount', models.FloatField(default=0)),
                ('down_payment_date', models.DateField(blank=True, null=True)),
                ('final_payment_amount', models.FloatField(default=0)),
                ('final_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Needs Bid', 'Needs Bid'), ('Awaiting Customer Acceptance', 'Awaiting Customer Acceptance'), ('Job Accepted', 'Job Accepted'), ('Job Started', 'Job Started'), ('Job Completed', 'Job Completed'), ('Job Declined', 'Job Declined')], default='Needs Bid', max_length=2000)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'verbose_name_plural': 'Bids',
            },
        ),
    ]
