# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scheduled_bid_date', models.DateTimeField(blank=True, null=True)),
                ('tentative_start', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('custom_down_payment', models.FloatField(blank=True, null=True, verbose_name='Custom Down Payment: Blank means default down payment. Enter -1 for no down payment or any other value for custom down payment')),
                ('status', models.CharField(choices=[('Needs Bid', 'Needs Bid'), ('Awaiting Customer Acceptance', 'Awaiting Customer Acceptance'), ('Job Accepted', 'Job Accepted'), ('Job Started', 'Job Started'), ('Job Completed', 'Job Completed'), ('Job Declined', 'Job Declined')], default='Needs Bid', max_length=2000)),
                ('billto_name', models.CharField(blank=True, max_length=100, verbose_name='Alternative Bill To Name')),
                ('billto_street', models.CharField(blank=True, max_length=100, verbose_name='Alternative Bill To Street')),
                ('billto_city_st_zip', models.CharField(blank=True, max_length=100, verbose_name='Alternative Bill To City, ST, ZIP')),
                ('billto_telephone', models.CharField(blank=True, max_length=10, verbose_name='Alternative Bill To Telephone Number')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
            options={
                'verbose_name_plural': 'Bids',
            },
        ),
    ]
