# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='actual_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='down_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='final_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='scheduled_bid_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='tentative_start',
            field=models.DateField(null=True),
        ),
    ]
