# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='billto_city_st_zip',
            field=models.CharField(blank=True, help_text='Alternative Bill To City, ST, ZIP', max_length=100),
        ),
        migrations.AddField(
            model_name='bid',
            name='billto_name',
            field=models.CharField(blank=True, help_text='Alternative Bill To Name', max_length=100),
        ),
        migrations.AddField(
            model_name='bid',
            name='billto_street',
            field=models.CharField(blank=True, help_text='Alternative Bill To Street', max_length=100),
        ),
        migrations.AddField(
            model_name='bid',
            name='billto_telephone',
            field=models.CharField(blank=True, help_text='Alternative Bill To Telephone Number', max_length=10),
        ),
    ]
