# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_auto_20170204_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='down_payment_amount',
            new_name='custom_down_payment',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='down_payment_date',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='final_payment_amount',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='final_payment_date',
        ),
    ]
