# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:10
from __future__ import unicode_literals

import bid_attachment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bid', '0006_auto_20170217_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('filename', models.FileField(upload_to=bid_attachment.models.generate_filename)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.Bid')),
            ],
        ),
    ]
